### ISSUE TITLE
Add framework to front-end

### ISSUE THREAD

**Issue by eosza** [csci4950tgt/frontend#20]
Discuss/add which framework to use
Suggestions: Semantic UI, Bootstrap, Materials?

**Comment by rafibarash** [comment]
Bootstrap doesn't work very well with React since it manipulates the DOM with jquery, since React uses a virtual DOM. Personally I've used [Material-UI](https://material-ui.com/getting-started/usage/) and I love it. Read pretty good things about Semantic UI also
