### ISSUE TITLE
Show error when navigating to non-existing ticket url

### ISSUE THREAD

**Issue by rafibarash** [csci4950tgt/frontend#49]
The app currently crashes when navigating to a non-existent ticket url. We should handle this by letting the user know the current url is invalid, and give the user the chance to navigate home and submit a new ticket, or select an existing ticket from the  RecentTickets component

**Comment by ThomasRiddle** [comment]
In the current master branch, after refactoring, the website would not show the error from React, and the 404 will show in console.

**Comment by ThomasRiddle** [comment]
The problem is partially solved in #56.
