### ISSUE TITLE
Use only one package manager

### ISSUE THREAD

**Issue by alejx** [csci4950tgt/frontend#52]
As yarn always complains when `yarn install`ing:
> It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.

We should only keep `package-lock.json` or `yarn.lock` and only use one package manager. Since honeyclient is only using npm, I suggest we only use npm here as well, by deleting `yarn.lock` and always run npm commands instead of yarn commands.

**Comment by williamtdr** [comment]
Agreed - there really aren't any advantages to using `yarn` after `npm` v5. Will make a PR to address this.

**Comment by williamtdr** [comment]
Actually, looks like there's no `yarn.lock` after the changes for automated tests, and there's no `yarn` commands in `package.json`. So we should be good.
